apiVersion: ENC[AES256_GCM,data:fZk=,iv:Aa4tSI171QK45x8Ds6gWg/XncxSaoEdz6mCWN91TBl8=,tag:cJJZ/he0YBzq1xgNb7lXiw==,type:str]
kind: ENC[AES256_GCM,data:XxMLCog2,iv:Ljdbc1LfeouxHEnw7qehv8gWT9d2eNnsJJVaCT3ZhYI=,tag:tUKXhepbsOH5T/j/GRu9AQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:78YsKAzTbopU7lvdVrBvi3hbpoU=,iv:rp0m9v9Fc8/AxEQuxkLRUrW7Lu9fCqTQVPczLVxsGfw=,tag:8Q8X1/nhFH44qSGlytWo/A==,type:str]
    namespace: ENC[AES256_GCM,data:6y1T20pmTFo92hpC,iv:9+mfClNXn50TOwHJlH7AMTzpwj2B+7OEWdkDWJQJDwM=,tag:PeGOO1+W/OTF7Mgu9GqeoQ==,type:str]
type: ENC[AES256_GCM,data:C/sEcMKP,iv:a0i+TkR4MYpqMJTBxvABx5on/HiCaU40NeMS22FLpx4=,tag:8wXwn6Dtr7RPyv3sZZodtA==,type:str]
stringData:
    #ENC[AES256_GCM,data:tW4w8sqD76OfupAKKZVl,iv:KswNWbJPom+m0SqUEZAeBa6B9P6Lzms+9ohB3XIFDek=,tag:NF4D49IWWea1mkBR8stdMQ==,type:comment]
    postgres-password: ENC[AES256_GCM,data:rWnwvWZLijB+WRrwRgyNsa9T/wOs5J2M5Ei+NelhyZA=,iv:bxzZ1hEQ6gtlzsUWi6XdH33msn+K/TlPqlMWp2l5gAc=,tag:G1WM0z9Otmn4y0tSCezdZw==,type:str]
    #ENC[AES256_GCM,data:59hwc8FxED6JLSd9oX2hkKW/UeHdhPFWSTyG10GAIz/KysA=,iv:y99dV/3YmfKqhCo+rIoO5XtcIwV5V6S57kpP/v99v58=,tag:Ef45r7vvatc1KcGkfNaKxA==,type:comment]
    password: ENC[AES256_GCM,data:h4aQ0VW6YpTonkw46dWzkuoUydkfYvEN1SyawPRnyYY=,iv:U8DApcloaKWp8XfSn7KLWmJcm2+ERGyZK7RyPsXIYPo=,tag:7cKa88UdZz0VV6g5fUoHPw==,type:str]
sops:
    age:
        - recipient: age1u7wrq6yktkprvkce38vhz358fmx7gunkyd0aflvu84d3wtvrrd7qvqwe26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUHlaQzJRWXhmOW1ZWVha
            Z3RPNTdaKzhRYWZ1SHV0SVFZaVl2aFhlN2drCjFSRWF2ZHd2UklQeXV0eXp5TTgv
            ZEZTTnhudm8rQzFmWGJmTVJkeGU5cUUKLS0tIEN0Y1pOS1laVkRTZXZDQ0d3TGMz
            NE1hU0xPWGtSeUpjYnBzRnd1akRIWkkKIYDgwSLUFqTlcOoUPhyyC/ofqkSzuVq2
            CROf6OCfFBwjM4f7ChQ73MHOeFxCxhofEk1zB8cb8Og1cztYmte9Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T13:52:53Z"
    mac: ENC[AES256_GCM,data:oDnXaVpAqr6RgWYutMrosNhFsQoWfiXUJAQ1ErMMbJvYFwqjg/Ma5yLqWmUQFLxthDhkUDlqFRWntJnNA1uoq+hEo3k0C9d3BIfVd+Fz1Ed2nmoja26kQGfA/327NpmMu3r0L3fTTVr6nr5Cxff//Kazc5WgcwIxibQimxxu2bk=,iv:LqGjLqksUzRRILosK+I5F3BpkzDcgnR0ohx5IEmvw24=,tag:KBKtY3IcmOP/I2TsegED1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
