apiVersion: ENC[AES256_GCM,data:M4I=,iv:Aa4tSI171QK45x8Ds6gWg/XncxSaoEdz6mCWN91TBl8=,tag:WM38BqzjaCAw1UjN9iKjHw==,type:str]
kind: ENC[AES256_GCM,data:xtg4xhwo,iv:Ljdbc1LfeouxHEnw7qehv8gWT9d2eNnsJJVaCT3ZhYI=,tag:Vj95NClnYERHkYC7nB2wbg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0njmUVpX+8xKbXHgBI8FiThcOAg=,iv:rp0m9v9Fc8/AxEQuxkLRUrW7Lu9fCqTQVPczLVxsGfw=,tag:a6yAyTyNZRONpbIGO6YLnw==,type:str]
    namespace: ENC[AES256_GCM,data:6XNdQGIO1fj28uci,iv:9+mfClNXn50TOwHJlH7AMTzpwj2B+7OEWdkDWJQJDwM=,tag:0GzXPsGBVh3SQPy2BiJ3nw==,type:str]
type: ENC[AES256_GCM,data:Ylrjtfb+,iv:a0i+TkR4MYpqMJTBxvABx5on/HiCaU40NeMS22FLpx4=,tag:Tqp5pH0jEFsr2zaRkYqwGw==,type:str]
stringData:
    #ENC[AES256_GCM,data:DCpY8dfuo/az1J3qb3Ry,iv:KswNWbJPom+m0SqUEZAeBa6B9P6Lzms+9ohB3XIFDek=,tag:ZlMZq+pNzRYKtOGVL/AKow==,type:comment]
    postgres-password: ENC[AES256_GCM,data:WmP1IFcG1qto6PZc4Ekb+OKxFMLN15c77I0FQALKINk=,iv:bxzZ1hEQ6gtlzsUWi6XdH33msn+K/TlPqlMWp2l5gAc=,tag:AqtGa5Jm1Y3P84bHKY7eNg==,type:str]
    #ENC[AES256_GCM,data:ZZM+oWayMHWfRa6bqR+A/vVk6sNoZQOzXHp5oqhOJJezhGk=,iv:y99dV/3YmfKqhCo+rIoO5XtcIwV5V6S57kpP/v99v58=,tag:Fep7NzcRzHF5kIA8hjjcMA==,type:comment]
    password: ENC[AES256_GCM,data:z2mzdM4mz5IY7ISP2a70rIve2/c4e9jehr5QjWc8dwE=,iv:U8DApcloaKWp8XfSn7KLWmJcm2+ERGyZK7RyPsXIYPo=,tag:GCMt4UT9EtU3GZpYFNXxCA==,type:str]
sops:
    age:
        - recipient: age1hwehr5ztfavd0p7x7n4fw8gfvzl05pj2u9v80xwqvhgnnmdfkexqspr0z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Y1pKcmNDdTZDdXZEeURT
            OUcvUGo3TEhjdnBWVjUxandEQ1pobC84SVU4ClUwcmxHNWFBRElCb0d2OWZFaTJm
            NEpteExFVE9xN0ZmOHdjQ1RWYnlrelEKLS0tIDNIZ3VVbnprTW1PRTJWL24zczVB
            YWo2Y3hVNHNUN0VhNGhCQytucTdDUzgKxukWYZuG3PCULVmOUXRil6q40KMSuCEl
            by1UtDhn2HJadiHgwcGxD+1Rz+qRtrUOCVt2Wgsm3sdyGbBhHTk95g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T10:37:47Z"
    mac: ENC[AES256_GCM,data:0HcB/2aODixMdLG+tlF2l5ytqzOJScxiVjsHPVf8JToQsb9/27UMIJneKT8FVxLormgdwNCH5JmZvxoSnUb/jACLQoI9IE0N2hFRQ5rsD8XLHiqu6jq27L5YOjYHK7d49m3eR6lsM4hJhBzALpwnn+QPZxAf28FaO6bjYhFaOXQ=,iv:aDx0KVGZL1uEjH0xm3IBxLL9G6QrtJ93HqWqu36zF/k=,tag:2VLaSOWJaoiGVYVXrHyyYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
