# SopsSecret for shared PostgreSQL credentials
# This wraps the encrypted secret and will be decrypted by the SOPS operator
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgres-credentials-sopssecret
    namespace: cit-postgres
spec:
    secretTemplates:
        - name: postgres-credentials
          type: Opaque
          stringData:
            #ENC[AES256_GCM,data:ojQm8yF7JJpC9lA8tZcHsqx+Z6Sd+eYLY+3vYH12,iv:l5MyEoFDTWWI71Wa+wfDfOyZwENYTytbsl+SDg4UvtI=,tag:pXTOuOrlJ4A1/IE72jmchQ==,type:comment]
            postgres-password: ENC[AES256_GCM,data:3AKAZ0gA/AZsnmr4SYUXmqTH0Tx1W05/oYTzVwL9IeQ=,iv:cnbF3bwH6ba1DpotohcCt3OqPUQpp3FwtPYNP1Gnbdg=,tag:PgXdMUKzGw6GIThogGI4DA==,type:str]
            #ENC[AES256_GCM,data:NiuVbAaisf4T6EyOjs2qjsXads3l9ODiAAwU8/M=,iv:1ZTa2jwj7wTdtuyzWknKsOxzrj4JhPw0SM7McZnfW80=,tag:NFehUpnyBdv62WXeIlZnTw==,type:comment]
            password: ENC[AES256_GCM,data:acETdXotcds2XIRDap5E8VUdn21oSuMYS47QTlT9qhc=,iv:DSyf19YmELzSXjZaZsc7rSCnEVmD3Z9fj0KJ51wku2U=,tag:rFhTJo8VRjXwKKddeH0iSw==,type:str]
sops:
    age:
        - recipient: age1u7wrq6yktkprvkce38vhz358fmx7gunkyd0aflvu84d3wtvrrd7qvqwe26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VHVOSlBabWx4M2YwTHRO
            QXNzUXRsQm9mdUhxTThNdWFHSmVFckJSbkNNCnNwNm9UQW9TVXFESmxDMTZHMy9U
            ZWN3ZHlobjcrTDdPSllCdVdmclVSWmcKLS0tIDU4bGpLSy92ZkVVRlBQbTIxYnZY
            Qy9tS1ZGdGRia2JaTzl4Nk5ZTTQwQjAKUcqEpJSYWZGKidsEtwLlkj7wWrTUenag
            hYeAGwpD9CJ2OzUFkoBBn+cWsUKyXBSHfu/f6ZVgS75OVpV5kTo3dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T15:14:07Z"
    mac: ENC[AES256_GCM,data:UWZWnrh9LKc4Ie9F7IRi+E8EPJPDl7dKkMmL15UUlunnFCTtHXKcwbD93q6IKerPLNrsqugzeeimf//xjdfXUKDw2nxEE/DaO3vUcSwtqAeNJFNG8JdS6TDE82+Erm0B768jGdHv3fA309SV3ZcGnmMPb7vnCWjgEXuAxoN0kkk=,iv:BPMJepSjm4aLo9fuYuYk8GFJrdu2Umb7M/zLhEygsBw=,tag:6cEIS4Y7EGKqNn9zCV9hhQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
