# SopsSecret for JupyterHub secrets
# This wraps the encrypted secrets and will be decrypted by the SOPS operator
# Note: Only stringData is encrypted, metadata remains readable
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jupyterhub-sopssecret
    namespace: cit-jhub
spec:
    secretTemplates:
        # Hub secrets (referenced by hub.existingSecret in helm values)
        - name: jupyterhub-secrets
          type: Opaque
          stringData:
            hub.config.JupyterHub.cookie_secret: ENC[AES256_GCM,data:0NEi63M3O7YEaQpti25RsWgaCLznbv9X+jM09srzc0RqNz2uoLzFJOOIqRCme2FvASGvPEAgfdzUBFE7t1gMuQ==,iv:WJpohItSEgLZ7H7vLw3H/H6UT0AuyAqnv+4ixwYLsEU=,tag:Gu7bvM0ws735+hZ3u2pfyQ==,type:str]
            hub.config.CryptKeeper.keys:
                - ENC[AES256_GCM,data:CJQQ9OQF2OoJNh+mGJiJRT4GcezYVADnE4fdksbfSjR3cuQp0Akjuwb52U+zGCr08j4TzK4rWfdjnBqRHUJx2Q==,iv:xuvfFkUmb0Iu9tfYSvnYo/qJ3EEo4heuB7tJzgfX9qk=,tag:yjvwIkJwwRJ8Z7C18QJ5WA==,type:str]
            hub.config.ConfigurableHTTPProxy.auth_token: ENC[AES256_GCM,data:A1qku8/pKguFeofk8Qn534YGOWc9BJSHId3tK+DJs+Tvi/h4fMFJqNxOQzT8sVH0OH/iP+8WQeeUAxwzW4FTfA==,iv:xHTl76em/JEodFbAl/REF3T0630DlBLY1gQAar2A9Vw=,tag:UHBJMUY3nn9+JKDPQ1xSCg==,type:str]
        # OAuth client secret (referenced by hub.extraEnv)
        - name: jupyterhub-oauth-secret
          type: Opaque
          stringData:
            client-secret: ENC[AES256_GCM,data:nOvCZ8FSvpJfvAQ+ga2CVrGV4UnwaAOGgLmiBH9bHT1F8VSFGrPm8GwwTUAh+XKS+0zekRx3VEJDmJNVNnDEMQ==,iv:AjNnWmPceFvm0GAkggthBY/wA6SHRZpnCYaSUabqdsQ=,tag:Rh23k/k0GdPHzfA9dmw3BQ==,type:str]
sops:
    age:
        - recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WDdWem9DWWlSVDcveEd0
            RVYzTUhRRDhXNHM4TnZqVnpXZHViMDdFVW1VCm5SbFEwaUxROEFQNUFKQ1VwWTVQ
            eTR3ZlIyOWROZXdCTFlYTmFzKzFWRmsKLS0tIHpkVUV2cC9rMFVESEZRbkVERDNJ
            L25ha2wzQ3hZQ1ZkVjhxcjVmcVA3a28KwsgnfpsWhBwwypkj/6Im5pREwfuYfvXj
            bWc+4mkcUZESyZW/4V1iczTvGXd3V4fq0A0H8Cn4CcTYpfAQ1/4+ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T18:07:15Z"
    mac: ENC[AES256_GCM,data:9vTy3vy+Kqd+2E0Eco+T/qKR7TdFufi+Eo1N7aubQy6pvLyFFjm2XMnN39BC7yOaThL8AkJ6iZDelxMi254SoOOWur4PMp0AUrqvWeViOK49ukk/CYAnvT5tH/gHk0HZFYgoa5GJnBBJbv0087s/nFX9dqqy5eMlyy51x2pdI3g=,iv:Lzc3usTZRbX8/lOAeOyiAW/QibTZpUSRDWEgk+sw+lI=,tag:R0yVsdn7zH74JfwMCV1nAg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
