# SopsSecret for JupyterHub secrets
# This wraps the encrypted secrets and will be decrypted by the SOPS operator
# Note: Only stringData is encrypted, metadata remains readable
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jupyterhub-sopssecret
    namespace: cit-jhub
spec:
    secretTemplates:
        # Hub secrets (referenced by hub.existingSecret in helm values)
        - name: jupyterhub-secrets
          type: Opaque
          stringData:
            hub.config.JupyterHub.cookie_secret: ENC[AES256_GCM,data:0d2D1cAwxQey2cd3uV0dsGc4Oodg7nA/lV3Hd6nmwUr6vRzU2wbombfjYoxHn3E2RwBewhbc56zg478ThXfjYQ==,iv:xszUrEC3ts/5nWcflGFfUix5LPEUqlt8eH7xVJzPF4Y=,tag:qh0fJmW1AIQ08fJ3z2il4A==,type:str]
            hub.config.CryptKeeper.keys: ENC[AES256_GCM,data:O9Yy2hHuHN+gW08qHSoKQxuEGO1Xo+9PidiuBActjfKbyQWaEzJlJEXZQxOXw6TuCpnsFgNeDIELstnpmK9RUA==,iv:PnUQG/TLHiILdjTVVjf1blxdpyiCaWgowPaTMqnUIOg=,tag:xpgsvmJGSQBw3LBTk9zVoA==,type:str]
            hub.config.ConfigurableHTTPProxy.auth_token: ENC[AES256_GCM,data:i1a3zmf7eeOCVH3N/neZhPJpQ12GE65K3RRQkhQ8Oy1JppTOmMmh/h53p9QeIt/nIJYPYVq90N82oxPUe88LfQ==,iv:4Gqyc1ZYUD4x2obmMTf/y/rhtCzmSJ1QNr0wD9SgeKQ=,tag:YB4e8i0ldJmlkOY4WNNa7A==,type:str]
        # OAuth client secret (referenced by hub.extraEnv)
        - name: jupyterhub-oauth-secret
          type: Opaque
          stringData:
            client-secret: ENC[AES256_GCM,data:v9p92lnhFZuAxZPD/cLzZKV0ViLfoaDHiLwC8YnLdZCFIaaGaS8dlBNd3F6JY7fdYZnt02H8kbqcccRbKUjojbD+pB5Ctg7/LgJ8o+E/97zkFx6eJVrtJzFQ43c8JKPAFVNJuFTids/58fzwy3Sdg0b9ADVSadmj8GwHDwSBfss=,iv:TYehI4EUo3t2S/FxcjbDOenlcxSFgBG4xdN1bB7aQZo=,tag:7ripXOTwifmQks0XjEqtSQ==,type:str]
sops:
    age:
        - recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUStiUzQ3L09IQnVZWTZM
            LzU5RGRCNlJJekV3dTdtTVNsb25oYkZibG1nCjNJZU8zcVY0c2M0TXlJdnlYcUkr
            TmdVQ2docHRTQTM0SFUvbmNFbnZsdmsKLS0tIFlOZDlYTFUydjRNV09OeVJJT1R2
            MHZYejNueWJsUldVRGJYYjhxZXRTYkkKleMK5PaGd1SspOXUMV5tWgZBPnpLa6OK
            vuSdPDbIk6qKiPp14NTrZIj/I25PLExi7xbViJFFQobmtIGXfpe2ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T19:38:42Z"
    mac: ENC[AES256_GCM,data:6ZIHGRe/6NB49fVMFWobO1YmMD+Bwld3m/d3sqUeT0yBhrbW0cuX1f+ZbXqSdZBO8f507vZc9sxZff65adAbiLNXwfANKgbiJxklLzC6MMulZjmt6k30aSqEuBOR7iAg/g52DXIxlMoG+AASWZ5CE4wFYzjyw1hvdmKra8dJB3U=,iv:kswTfNntcbqYFHv727VqmqPKHefT6Pz6qYERQ0bxDYY=,tag:5/xKG6pJCmoW0+C7yc7ikg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
