# SopsSecret for JupyterHub secrets
# This wraps the encrypted secrets and will be decrypted by the SOPS operator
# Note: Only stringData is encrypted, metadata remains readable
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jupyterhub-sopssecret
    namespace: cit-jhub
spec:
    secretTemplates:
        # Hub secrets (referenced by hub.existingSecret in helm values)
        - name: jupyterhub-secrets
          type: Opaque
          stringData:
            hub.config.JupyterHub.cookie_secret: ENC[AES256_GCM,data:m5PSFr/QlaMbIaFF+030vh71Of1ObkD5r/JkqpYVXOJiDKhWB30ksmBxYYdVST9nowE1sJ3xZnLbBuyvlKkA9w==,iv:B26MLzM2YRTtulZByXp0/mRomfcHlZ37uD5d2yQP0to=,tag:2+IuWAX1GJ77vfdv6cC7Ig==,type:str]
            hub.config.CryptKeeper.keys: ENC[AES256_GCM,data:vI4HUgXrzu1wicSCm/TNCADF5EGmyFo+iZonTjee0ktu5eBj/PttrhQDChS78uNEPOp/5p0ZcU486bXEvmqTkw==,iv:jmx38UBUJN30lwQHpYJbc3l3cYVXhj0L3BSWmv3dFlc=,tag:1abNJTlNQ7+aKH50UMJ+AA==,type:str]
            hub.config.ConfigurableHTTPProxy.auth_token: ENC[AES256_GCM,data:wWkwtJqWupClLd4nHnXjXcwEN435q2zMVeK5/CYdb8NBqdc8XZxNexxSQNVngGJ9i/TcBQykaiGhLK3/ItkRWQ==,iv:WSknwrYm5xyCYAAWlu6AxFP4UeCgmbCu0fZVy7ZnlOM=,tag:g7WSrpBmcYDursbARXN8FA==,type:str]
        # OAuth client secret (referenced by hub.extraEnv)
        - name: jupyterhub-oauth-secret
          type: Opaque
          stringData:
            client-secret: ENC[AES256_GCM,data:YcTkLryyPQazB2lCkMMYXrSSWeC2pheKSACdpf7cvrvzD2KynGWYlA14mfdVBY1T0qtkg2SndowFDo8FHWUDMQ==,iv:ZePSj2S+K3bx994MXkyEoAsgb98xaYF731BwhX+5i4k=,tag:PQduqbiNJRFX4DpIn4LKzQ==,type:str]
sops:
    age:
        - recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcGVMOTZjNEU5R3Q4dXJI
            U3hzaHhITWYvNTdnNDB4WURaTEgrS3hWbmpvCm1kTklZT01LT1JmSXM4K2cyMndH
            emtVcEF1eEhqbU5IQWZjMUJiRXgvaDAKLS0tIEdocTRROWFQMFlHcGkzOFdYY0Ix
            M0kyZm14SXZtUmtjSXFKdGlMNlBVUVUKhOca3n6NmKSOhm/ThwFxCetYODeFFSpo
            KG1gneSkRZikLR1x82+wew0JeTh7nIDl5KEnn3QP0+VmYOzaKhJGGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T19:25:46Z"
    mac: ENC[AES256_GCM,data:SWUXucqNzxSyJ0tWlrP8wyQpSBkHWUvGVyTMADiY52qhH6NV8iiV1fApjho3pCXXQnVqsDtcZ2JatEhGX4lloV31oIwroAsRRS/z3rFKLapIl/g8EmPlQ2yg7pbK1qYN9KKK8VzPXm6Dmd1PXaVTii3k4ufSkSzG/GKkkeR/CHI=,iv:Ie6VWTUSNG8EpyVK8Ld7pOJud9VNVlA/BNWNhNhYRd4=,tag:I0un4oLrLdfH13avYZ0I2A==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
