apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-smtp-sopssecret
    namespace: cit-auth
spec:
    secretTemplates:
        - name: authentik-smtp
          type: Opaque
          stringData:
            AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:Q9V3xNlaEu+fIeqihNpxgD4=,iv:173r8AzedpSDyuMy4YXOEt+EggVECu6tcyKUqapXsDM=,tag:iAINJKPGjQ0t8pAN3kgkhw==,type:str]
            AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:GKcn,iv:elTggVcwFdMF1fZ5Vwwfw0AGBdf2JH0ycsxRgkGX10Q=,tag:+3/1CEzBKzeh7p9mZD2Mfw==,type:str]
            AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:oGqmyoMOYAm04UWb5oZ+Il6ZHDo=,iv:jvVGfEeZIoI4TxtjxkSRtFq9+gl9YwFrnDUcNO/Bp7M=,tag:7ZneKHwFIyig/rhrNz1/4w==,type:str]
            AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:p/eXNAJOJigz5LZBdp3dg6xRQSRN/RhAIxWtWRhaomMwjYes,iv:tgNAEu5kcCJZAi9LrJkUxPQxe6Wr3L/Ek3Oj0dm8qMo=,tag:JaJWULWIeAwv5DLTVYDq2g==,type:str]
            AUTHENTIK_EMAIL__USE_SSL: ENC[AES256_GCM,data:7MQOfw==,iv:lWNjCtpDyOXJcy54jdfxB1Y+yvzbncNTZxxaxOm6Nb4=,tag:itwwwhEQIq5RnCO+2bSVsA==,type:str]
            AUTHENTIK_EMAIL__USE_TLS: ENC[AES256_GCM,data:tIFmqVk=,iv:HYyXP6b+zeR0rYrHyqmz7pSMkzgWKvizs3WU7ksjOuw=,tag:qZd1TFrg0z0wATst26Pg4g==,type:str]
            AUTHENTIK_EMAIL__TIMEOUT: ENC[AES256_GCM,data:h/g=,iv:HLWnXu43d2i4yzsB/gJA+gcSsgeeUxeTYto5mWc3zvo=,tag:nr62xBhAmo4eVYntq6Zaxw==,type:str]
            AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:UBUt10SLLwoJHDP5o+H6i31E0Bs=,iv:RN7iHTBCm2FUAdw3jQnjo5IrtOd03RfaeIBOg6bO/PU=,tag:z9RowkVsF2Kc3ZVkevI1Ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWVk5b2R6Vmw5VU1vUDdF
            U0Zpb0Q2bTRsMEFHaVRSUm13MDJKbVBSc2lBCjN4N0xIQzVNTVI0K1NxaEdWbHYw
            a3pxMldmSDhrNjVyQjhLRzg1c3FvSEkKLS0tIFJRamJIdTJJTUI1Sml3Q2ExMHRy
            d0EyUENZaXFQMDI3amw3cW1EUDhZdjAK3mMUyacq/zVRk8jswK0XRUSigQoZFeS+
            g1wE1/cUCCr58vphPJVOoi6sVPDNO50o26/lI5zvhG079Gl8q41YFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-10-06T06:55:29Z"
    mac: ENC[AES256_GCM,data:D1VfDhthaOYXdKetw0nroi22GLJuopMR6eKZBuYv1jakFFmmd+gzS1ekTD9RJCYDXlPv57HSJsK5yn8p+e3eZznZEWBjHCiGjnnod1cgJloFSaOjMk9Y53hWITm88xnCPgRySqNRBsa0TCeOT5g6QQu/XNLMSufg7dvDYla552o=,iv:0CaF5FYIEjkF+t3W5KeGPawuOEx1NYmBLSN6gubOng0=,tag:VH6vpPKZTdAZb7N63ljmpA==,type:str]
    version: 3.13.3
