# SopsSecret for Authentik application secrets
# This wraps the encrypted secrets and will be decrypted by the SOPS operator
# Note: Redis removed in Authentik 2025.10 (https://docs.goauthentik.io/releases/2025.10)
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-sopssecret
    namespace: cit-auth
spec:
    secretTemplates:
        # Main Authentik secrets (referenced by envFrom in helm values)
        - name: authentik-secrets
          type: Opaque
          stringData:
            AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:CsRcj7ZhBj/hQbeUlG3rctKPdyj/8TteDjMNxfFdSRZ8LV5g259VYNTggxBpzO2uWonN5crHGy0a5VjDsUqrlg==,iv:DN88t9LgfgYldC+E8elY3uqeLZMnwMUEvEeuu3EsvrM=,tag:WmH/7vZFjjMytDqtTDIzGA==,type:str]
            AUTHENTIK_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:KghdTyLQCQwP9JhAxj8NTdMrEYkK0s3sc0KVf19QnD2NHS4fneVXwbRZO4CIao7WmIjEZAgJU5SL86pvH/Finw==,iv:4C+O9MeL5sIUEiFGNWeRej6jKJ2+mCDMXH4R7vIEO5U=,tag:LMhbBU2cUO437iggVCHYzw==,type:str]
            AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:n61MJt0cRpMfn48/O2cxkr4QdSQ3CWsHJwlg7QOF7MB9uwBQtcb0JpUa8V7FQfWKnJ40N/63nCSgpgOfGCOMkw==,iv:xyLxdHLyXpflIcYSZANpCJOIjWzFGmrzBCAQIvd61b0=,tag:3VrJRIO+WMJAkoPRHyHCJw==,type:str]
        # PostgreSQL credentials for Authentik
        - name: authentik-postgres-credentials
          type: Opaque
          stringData:
            postgres-password: ENC[AES256_GCM,data:z6LefWhBYw+Qvf2kJzi9gaK6L1mHQtgaMq/coxYVv6MIfwRLouySsuAoRpJO+SqCw7tZZj3dQUndRzc7pND6kA==,iv:ZKUkW59r/Dpt+UDMwYwZSB9TssfxgfYZuZi5MIXcVLo=,tag:98xynUUIZja97RluC6qW6g==,type:str]
            password: ENC[AES256_GCM,data:iItPgMRbxJHnc8YO1xkDer22/vhi6H5fnbr1uZ25A5M2Tpfe8GFzFdTqLzsPP21pAYK4JIuCIKpLWxdqCssuuQ==,iv:m+Ynx0jSbEiawtxdiD0d3RQuYlJWbKEli1W+yZK1GeQ=,tag:+ugJIf0Nz1pp3UW+ZRp/tA==,type:str]
sops:
    age:
        - recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eHBRV2RMRWVTcXAyQlZD
            c0ZOS3JiK01qVjRiajlIdjl0dXc1bjVVVTFZClNYc1QvcmgrdW5rekxYWFNxVG5K
            ekJvQSt2bUFYTHhheER5TWZ6QVB5ZHMKLS0tIEVGa013VERVcG5nS3gvRzY0VVBD
            RnZEc1N1L0pyK2FmN0RWNFFUOVRiTzQKQ42Zi4t1gzKnfRo9ehPeOQ0App7TrDzl
            wcCJhh/AyyCbiYbq8Umj8to4nySJA6zHq5aNTiCO23SJTb1bRxPlvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T18:07:15Z"
    mac: ENC[AES256_GCM,data:nwr1pONApd68qkVioQFVjoU76dBWA0oFuxNxCh21AjXMAFCmud30/3P5ZRHYNUMh3GtEKmoHGtlkU46kBpRONLSQTWjJc9yXrs39deBV8kC1j78IbwgZ7voXkq3fLoQUCx9GAl7W5/RXStPsfbnofA/vptqOGxi3x56YyiTOo68=,iv:UQq4ANpxnSz7xTp5699PHB23gXezip7vas4X5YLZUM0=,tag:9qrOSXgekroxTuSPFBkNTQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
