apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: harbor-cps-users-pull-sopssecret
    namespace: cit-jhub
spec:
    secretTemplates:
        - name: harbor-cps-users-pull
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:eVZI79zD68Hru8vvRMEWAuZpGivsu0ax9orhM66WwXs7zKcn/XrXdIRPHqgC6TsGtGh7xyFiQloThFDrXKC28nwO4ym7zBczZgG4hmj2D9VjUSTUm56UE9XZ9/m/8ZS5aPZklfBpyP4brmuUqsP59NZH73C7aicj/5rLrxX5N0r8typfCry5k47aDb6OQq7TyuijYG6ra/IF7isz5VeQR56M5mAuOT8jQYN3VhQposDk36wbud7YZ4F4KgzFzihzmU9d/s1UXfddlfK+WPywhGCaxA==,iv:qVJmL82IMWA3IcvYIyd5QHOAd5/lKeCVpZScKGbS9m4=,tag:iAIU736w16lh7FkeeTSsYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5a1Uxd1Zmd1o4NzM1OWhN
            SFd1Um85OWI2Tzkzc1UxbnNwRDhZQzA4Y0FVCkRyOExQZWNsUkZBcStIN0RaTkVC
            LzJzVVVRQWtvUGdiaG1iRm1jN2tlTjQKLS0tIHFNdHV1V3YxTTdUemlDa3hUR2Jl
            anpPbXNuZDBZaXJsMU8zOEF5cFRIMWsKHu6Tx7onjUnHXZXAF6JLmb2Lruagx8W+
            OnKfG1fO4l40NgV0/ZKZrF46P7t5IgE3ymUWNLJC1YHvrhMsVbe7Mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-02T09:28:28Z"
    mac: ENC[AES256_GCM,data:S2IcUXsGOhdiOT4hXdgVpa+PKDGhv0VCWUFw2miQocutwkNkfmt2QfoCcjqD3HKd3esohj+ozdJFfXAQFFyC18cQIXRWsDQp8AlDDG95VCiLNX2U+z9dpWclSpX+lTDb7VU8RfMfcsgHG4B9kzE54qo+eb5JNFChrgwFy+WpV5w=,iv:bLrIuQXSrHm2vZ9KfCW2Jm59tC+a67NULujxxFH03WI=,tag:Ikb352U/INbO8sWM6EQy+Q==,type:str]
    version: 3.13.3
