apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jupyterhub-sopssecret
    namespace: cit-jhub
spec:
    secretTemplates:
        # PostgreSQL credentials for JupyterHub database
        - name: jupyterhub-postgres-credentials
          type: Opaque
          stringData:
            password: ENC[AES256_GCM,data:n9GNaaetCd8HyAFI1lJ8iAr2rXYEa8mnNCtXbJ5r3UDjxapcPIoSHdTHcZ0=,iv:s5ijxryVS5eJYPU8zc4HaOJ21WXustUoRTIZaBXv9iU=,tag:gTYTX8SPSOeu3Vw8CVJ/Dw==,type:str]
            postgres-password: ENC[AES256_GCM,data:mtCAyBiZvNFnKJhXD88uQdW4Krks4etTpMNTqF0/ApwZtvseHMHIy+XN+k4=,iv:MSOt/4WgyLhq2OSslqXn/TQcq72clhffAbJ/KwI6D3I=,tag:ccdbTrMdoeW+QBHCatvzRg==,type:str]
        # Hub secrets (referenced by hub.existingSecret in helm values)
        - name: jupyterhub-secrets
          type: Opaque
          stringData:
            hub.config.JupyterHub.cookie_secret: ENC[AES256_GCM,data:s3lcdaFoyP/Wj8KraMW2FPazi4S85l82RMBWF1i4KJFYCwrK9H79yzbWqA9BLOC56ypoKYDc4px5opL3n2JYDA==,iv:9DSgEZHb9s+4pGhtUNFgMRPBZD2vCh0ZGGV6BfRhA1w=,tag:LE2JtvascKEeZeUrQkjcUQ==,type:str]
            hub.config.CryptKeeper.keys: ENC[AES256_GCM,data:PYzWnZLO9fm7SNnDzKBfwVjN1mjQTMAOIFM43YuhJ8eZH5PTrwGsd3RaZRJP5tUdzc+Q0iCsioi8OQsEjgJ8NQ==,iv:btdJ4VYaHIafOA83i0Yy+p7dt/xGDm4qK6p9N0j3xFg=,tag:9g0QJ3oMx/IrH+/KLXTiRA==,type:str]
            hub.config.ConfigurableHTTPProxy.auth_token: ENC[AES256_GCM,data:DW1eA/ZPC9ueHMuKoEQcU8PQ4SOMrIgAa/PPjPGeEJmg8mbCoa4leYNd5t0bsOtxwwTRz9rcdHhofNUt5wKqJA==,iv:reoF0v0llKoVYdwLdnRqs/pe//1mPdzypKjyHBKDsd0=,tag:/oVTByOBUnQuBF/KKq3jCw==,type:str]
        # OAuth client secret (referenced by hub.extraEnv)
        - name: jupyterhub-oauth-secret
          type: Opaque
          stringData:
            client-secret: ENC[AES256_GCM,data:2c9Q0ogBHgSKA08SiJlGJPVml6CW2ccGZCebYRBep92mq4j53VgSgz24QUG4xNXtlFhNW7Gvt/p4lBgTw7Ny4Q==,iv:bBac6SmSQMO1oiQ56w3AzKJ8aYVt1tVl+ee1ScF5giU=,tag:8Uei9ID8w4cwsyRwWO/skA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QTB6RVFWdnc4RVdaTWMr
            bVV1cm5KVVFQY1JxYitMQWwvUGhJdm9Ca0J3CkFaSCt4N2FLaFlSdnIvaFFQN2hr
            blBoTURWemRTWXJqbVAvY29qVE1pbjQKLS0tIHNCKzBSUlJKRnZBakNFOTFmK2J1
            Z0x2Y01VUFFsRUppZTd4UW11WnZUaDgKUcwVPH/l1VSW8NeMd0yeem9dPZuv6vBd
            e95eZrdgflhRY9hoKYO0XQ2a5ZRB/CN4KVZoh0smZf/0xucM7p8/sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-24T08:36:11Z"
    mac: ENC[AES256_GCM,data:kKD42McDe/7rYwm+pTFzwWGm5DPwEmReEHhWXe3C3r3WgSG+EU5AlVWnzIzr5Dxsy4aHJs6ZgMjlJICAxeGT6oCO7GpHi6GOEV49e+UkhDLALqvIAZFZU+pMoLFEjucWlEpsIl6p8mizhHmP5rl+6B1Vycrg1cb6ShVtQZzPNBc=,iv:wVK9aS+p3PPBVfF/W377CS4omzejiJarReys8rt8VmY=,tag:FJ4qUMpDZDQXj7JGLyH4Wg==,type:str]
    version: 3.13.3
