apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jupyterhub-sopssecret
    namespace: cit-jhub
spec:
    secretTemplates:
        # PostgreSQL credentials for JupyterHub database
        - name: jupyterhub-postgres-credentials
          type: Opaque
          stringData:
            password: ENC[AES256_GCM,data:8K2cg9wrp0EhpMOCDFHvulPkQnpS+qmPZ3JQDuWYJJI+elFwcwK7m15e6Qc=,iv:72BngeX2EIj5MlJ2OsnLjpvSnx4U2II8GBHaPIaPQVU=,tag:7fNZibhe9Pg4W0nzovXJLA==,type:str]
            postgres-password: ENC[AES256_GCM,data:x6SCWl8SgqYFs1jRme6TC86ZthncjNYA8EiqT4yAnxz0EuFxlvl2dqlEozU=,iv:lvz+wdfIx66pCPz4P/vFMU4yuxzBz4HaxtJ+OYHy/3M=,tag:t3eRlLhB0hM66lMellHwvQ==,type:str]
        # Hub secrets (referenced by hub.existingSecret in helm values)
        - name: jupyterhub-secrets
          type: Opaque
          stringData:
            hub.config.JupyterHub.cookie_secret: ENC[AES256_GCM,data:qcBrrXCB2M9LSBx6w6AHv/vdpSMP6y+rzElo8A8E4vIwlcp4Q+9joidt1o9FdbPm+kllogQOUpPrl6QJ8SBeaA==,iv:RzH+7Iq8X1QF35H2W0+iqMTHKO/Rq2/xVhCOYTSAnws=,tag:+TC7BnMDu4Ds3KbCq4voUQ==,type:str]
            hub.config.CryptKeeper.keys: ENC[AES256_GCM,data:6PljsPL6CG8MF3luhxEGgftdAB0e4MKncxFIcFak/Mi+6PIf4YzMAlNa8RYk6AIxDBvY1k5JSmEfPcvwgyN73A==,iv:6llPODCawPCfcKNGWlxe2bVl9s/P8ia9kCXPBMIpf54=,tag:wu91bbrRX1eIoQ8zsoUrog==,type:str]
            hub.config.ConfigurableHTTPProxy.auth_token: ENC[AES256_GCM,data:dZ2VWSBCB3LGKrdt6ond8DAMT+of03eBJ9vrhfQpHKHm+mT9E1Kh/9XpWP811WufpMQp+RePqt2OhgBU1sJz9w==,iv:xIEYtAkEDPZF0btSZFWFHSLAJqZ+ciRoaw9G/EWOEP4=,tag:OKkQQfUnXrIBCRUu1kwA+Q==,type:str]
        # OAuth client secret (referenced by hub.extraEnv)
        - name: jupyterhub-oauth-secret
          type: Opaque
          stringData:
            client-secret: ENC[AES256_GCM,data:AK1c5umRtcnqUo+RJHurL0gFGBuoUTkQsudJXVXD7u2Zh9VXsxEPXp6n8Jz5M3nsrzb5VFu70fZYPbMAyEve45TX1hPvVWbXqe1T9yq+eNKBbXwycs79PxqgMO01blZQCEvHOKes0VTC6EPaWM8iSWWMOTW/+TdHJiF6yP7bH94=,iv:eLBabdeLStaCBjq4VezwnYfvwO+Ny3bAoe+24vC7Z5c=,tag:wcf5yeTTMDt5bJ2qKcPqNg==,type:str]
sops:
    age:
        - recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPb29VVmt5RTFvcWRSYjJR
            WVZpMGFvYktVaXhqUDA1TXhVbGNaSHRQQkRrCi91WjNBWTlIODFuUk1ORno5djNh
            UExyRldNYWs5RlJDa0ROejduN3lhZWsKLS0tIERPbzhYOHRDd3R4RzNrZkZMdFlh
            U0ZVVW5xa2lBT1lCajRzdGRVVEloOEUK1/T6BtTyHFymCgcXKm1MzWh7lPxXT9Cj
            HxXHqkhyTQpf5XOtKJrcT9ezb7FUURpxVKuSI9NCDWIE9fkKOJutRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T08:33:48Z"
    mac: ENC[AES256_GCM,data:KdeujPl/jghGIVsFzUPn2YlwYQarfr0GUXtscCfNURB+RI4fgTEBOziAu+/Ggew0Ci3CLMHfjBJDeVylj38fcCFqWr15Iv00LwSOGOYAZw8oNWwMq3xWq/cTnLVWQ0CTnlxp+Aj8/SaGWosiWGVZH7u1F8CbifJ8NvQ+T1shbeU=,iv:E3LTKyFpkJwqPaf62nCCITfGKBIpwmNn9GtGOkkJb78=,tag:EBUUQLaeSD0BkJwxaKtspA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
