apiVersion: ENC[AES256_GCM,data:+so=,iv:aYA+ftn8wYiQl1wzz5g1RFklDl/z8FcXXJFhaeN4lRM=,tag:7OHXCAF5Hw5/XY7oQQwpQg==,type:str]
kind: ENC[AES256_GCM,data:2U18x9Yt,iv:+i9OIYRWz+KyoJqNgZhUIQm1GZagaCpeaqr4zrx/zJU=,tag:2V6OUBbMeEa0NFbDNdp6dA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IzcmDmF8gA+yDKxTrJX8qdeQJLp0bUY=,iv:V5s0mmHxNVKJLWNtiyZGdZ1NuvxNGxHX4zbLP7VmzgQ=,tag:LNdgvPr/L4VsFPnK3UCXfQ==,type:str]
    namespace: ENC[AES256_GCM,data:4lYQ0k5DyiU=,iv:3NKpnBJhwSYSlwS3ypy5yNZ9Y4FB94xvSHnsaiAhObM=,tag:kShVSkKMMAeAHU/le34GwQ==,type:str]
type: ENC[AES256_GCM,data:4TlGiQDq,iv:2HekUEUB5jy6zyFl7ivkPcfs4/UwTIlZP3be3xMIwSY=,tag:xzXq8ga+jmYtCl/4fvYm8A==,type:str]
stringData:
    #ENC[AES256_GCM,data:c4+QqRCTOkdK1BaFoVM0kKgkw/yDxcjfC2bxVX72WvIpy9s=,iv:UymbsV9OXs4yNmZZ1WvZ5DGszLhd65rAK7oRzdGe9Jw=,tag:LdPqe69KRpDLNKEV0c791g==,type:comment]
    client-secret: ENC[AES256_GCM,data:jecRZ0bKcNuyxYA1GXMPbhErWHY2bEZX7lkAYUEbCf3c3cSPUmkS8Q1nYb5BxN+veXs=,iv:Wrl+CD1trpGztp8MF5jeh2hPp3yZrxHQ9HBWUXlDRjA=,tag:2VY/smo8pfEDWrLkwPCIYQ==,type:str]
sops:
    age:
        - recipient: age1u7wrq6yktkprvkce38vhz358fmx7gunkyd0aflvu84d3wtvrrd7qvqwe26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcHRQSTRjeVRNT3BCWmVi
            MmQrZUZpU3MrQ1JQbVovZjZrWFNRMk13LzBVCm1xOXYrVy9YTkdHT084YlZLakdr
            cHYxUnVEdS9Bby9VOHJOYWNwQThOcmsKLS0tIHk2OE9PQ1dTV3d0SjFTZld0MkhY
            UXZKU2ZyL3NqRHpoSTBWT2dMcTVwNDAK9uXcJ04N7dko3r0khAELs0WbgKwcOLAt
            S0sLWmt//EHSBxZNVeBixzSv0U1/lD2IM4mOXtq0WMOrydFwmNripw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T13:52:58Z"
    mac: ENC[AES256_GCM,data:X6sNL5CRtHCEHg98AVKU4exE7KliF4DSHO9WEZuyBOmpWKLbWn1OZ/aw8RzOC6c7D/U8GAHKAstj65svJoX/k2aJ8ul0NM92GxIVZsvmuOrRVnQdD40ndBT6xxX3Jyw4D3O9K8jjRfzAHJFjSh8qFsdls1DMXE5/wjmodQZZXl0=,iv:BOlcDiDBisVVvkz1eWn1zgPOT5EyGK2fh4pHE2s2hq8=,tag:hZsdmTkX3USMyYZGLPFAvA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:+so=,iv:aYA+ftn8wYiQl1wzz5g1RFklDl/z8FcXXJFhaeN4lRM=,tag:7OHXCAF5Hw5/XY7oQQwpQg==,type:str]
kind: ENC[AES256_GCM,data:2U18x9Yt,iv:+i9OIYRWz+KyoJqNgZhUIQm1GZagaCpeaqr4zrx/zJU=,tag:2V6OUBbMeEa0NFbDNdp6dA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:a05MhweMzVlJYHQqEM/jGpOo,iv:8UYR0m9f8hOZ4xJvCpEkQ3Nq8rDDVrCCCFkDrtjpq4U=,tag:4seE3JAwT07VIgvcNP7Ong==,type:str]
    namespace: ENC[AES256_GCM,data:4lYQ0k5DyiU=,iv:3NKpnBJhwSYSlwS3ypy5yNZ9Y4FB94xvSHnsaiAhObM=,tag:kShVSkKMMAeAHU/le34GwQ==,type:str]
type: ENC[AES256_GCM,data:4TlGiQDq,iv:2HekUEUB5jy6zyFl7ivkPcfs4/UwTIlZP3be3xMIwSY=,tag:xzXq8ga+jmYtCl/4fvYm8A==,type:str]
stringData:
    #ENC[AES256_GCM,data:gRLbo6QGwenE5wNCzKD1Cq9FDZHaMhDiA2YwoGNAuqiQtsLC5LTnLO8=,iv:NonCkFDqKkVMH1R3EUsJD9C/Eedvpa2iF1MdwGLaI1A=,tag:388aRvd94QX4okz4VbIv8g==,type:comment]
    hub.cookie_secret: ENC[AES256_GCM,data:lU70LocjULrD39NCerzqNF7sgw3Lw9MjtAsjabRPgWuoQjgmSHExoHs1v8eMBGxSdnuQz896lE5jGR04fJkX+w==,iv:BB81o69voAkaZCp4RfhRGWAHLSCEfc9Td3BFlwM5J2c=,tag:v1btrw92REdmvu+yqceArA==,type:str]
    proxy.secret_token: ENC[AES256_GCM,data:OCBKxWVopBfVUazncxeaCXlCjHOUYCDGGfG3rxN0RnxdsdZcE89O8Q1+evSMnkY/DR20u8T9gcvVQqEstBet5g==,iv:ProIt3bseWUEry55wTDsr0zZGCgXxOvIKScP3sbX1c8=,tag:YOKB8GloOMO96QwQGNw6iQ==,type:str]
    crypt-key: ENC[AES256_GCM,data:15pEEJa2tLn6YG1Pdnxzk102vLhQDskBHCgdVKK8f+Ml3LMa42opPKh6OTUOub0P4j08rbLynyhkzlIYyd+hIg==,iv:rF9avh1+1sZViopscDxXK7z4BNrCOheyYfHIk9gOvjo=,tag:pgKuiefq2TAXsI2netEa1A==,type:str]
    #ENC[AES256_GCM,data:MbqvesciCAe09FM6JJqXE2vw4ohiOUVaf4A0kuojvowArimOj3/q9TyJTyCpWyzILGZGSC0fZhtNvUYLvVRJJHxb4KtjF6bL0WleAzxIZy0WCP0+Ww==,iv:9+U0zsbrWj180sdaw4zK0CjW955cflZcCL5gG9rN+P8=,tag:09LX5uWQSXGoERlMIbx1Fg==,type:comment]
    #ENC[AES256_GCM,data:O4cMwltrrGBHh1YQ6P9wWCRQWvuSoZb2tyNhUGg4ME/Y58vm79x6qXtY/6atXWd9DLk+CT1G83LMAI+D+g==,iv:XG/0cB9JBe5d5I252Mm+IRN5iNMzEKotNcZ2VfMkKkg=,tag:vJiJUM6D6TOb0cP+/GliOw==,type:comment]
    auth.state.crypto_key: ENC[AES256_GCM,data:1GkQifJKhVXPPsIM/jfXFNaNs31xDIXtU9RLVnCSUPHBXZg+3V8V3x2smw1cs8JPyWOuc8c9jy2VG4ssNfUWKg==,iv:7qR2q9Vr4JxmYRTdPk9Hd6D10u6PJkHHp4ZYpS8md34=,tag:iCfOi1q7Oo1RIx2RByGrfw==,type:str]
sops:
    age:
        - recipient: age1u7wrq6yktkprvkce38vhz358fmx7gunkyd0aflvu84d3wtvrrd7qvqwe26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcHRQSTRjeVRNT3BCWmVi
            MmQrZUZpU3MrQ1JQbVovZjZrWFNRMk13LzBVCm1xOXYrVy9YTkdHT084YlZLakdr
            cHYxUnVEdS9Bby9VOHJOYWNwQThOcmsKLS0tIHk2OE9PQ1dTV3d0SjFTZld0MkhY
            UXZKU2ZyL3NqRHpoSTBWT2dMcTVwNDAK9uXcJ04N7dko3r0khAELs0WbgKwcOLAt
            S0sLWmt//EHSBxZNVeBixzSv0U1/lD2IM4mOXtq0WMOrydFwmNripw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T13:52:58Z"
    mac: ENC[AES256_GCM,data:X6sNL5CRtHCEHg98AVKU4exE7KliF4DSHO9WEZuyBOmpWKLbWn1OZ/aw8RzOC6c7D/U8GAHKAstj65svJoX/k2aJ8ul0NM92GxIVZsvmuOrRVnQdD40ndBT6xxX3Jyw4D3O9K8jjRfzAHJFjSh8qFsdls1DMXE5/wjmodQZZXl0=,iv:BOlcDiDBisVVvkz1eWn1zgPOT5EyGK2fh4pHE2s2hq8=,tag:hZsdmTkX3USMyYZGLPFAvA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
