apiVersion: ENC[AES256_GCM,data:4H4=,iv:T3KKo2HBEkdrHa0oQTS7Pbf1OVOA+QWJWWhXenmpdfA=,tag:NMVeSVb8DqG6PAMjSG2k0A==,type:str]
kind: ENC[AES256_GCM,data:stWs1fd/,iv:tc3Riq78yiRBZXyTFDp1tGYXT1KUmysLvz1wAHlLnNM=,tag:2usWt/2ztDwQOhIltnj9Fw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QfhVJS7dWSDjS58iQpRumGDIbh5WAzU=,iv:V5s0mmHxNVKJLWNtiyZGdZ1NuvxNGxHX4zbLP7VmzgQ=,tag:3yNN16dPrHUZOsjAIjccgQ==,type:str]
    namespace: ENC[AES256_GCM,data:/SNfn8sdnMw=,iv:E8OrD80U4T6rb+O5fRHVTPE7Y/mEyaLJWUuOVL+xGwM=,tag:+rH67L+W+houo4C/G+5Y1w==,type:str]
type: ENC[AES256_GCM,data:JHCf/EMC,iv:O1QoKBp8kU9umgEljDOr6kdaAoNI4zAosUxCozyO8nk=,tag:uWeoA19U8qfiidlpYe5wrQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:vNQnHg3Fbd8R8xM0nYrYf2sa412V/NV/MT/N+kcM06Z5kiQ=,iv:UymbsV9OXs4yNmZZ1WvZ5DGszLhd65rAK7oRzdGe9Jw=,tag:ve4gGon/bmedL1OAwmXe/A==,type:comment]
    client-secret: ENC[AES256_GCM,data:VDj5xcQSuOjDN7LEVOMBOXT2sgi4Tf76Dwihc+wzCZeBpiVrf5Rxl7FICyRZ48zPJ44=,iv:Wrl+CD1trpGztp8MF5jeh2hPp3yZrxHQ9HBWUXlDRjA=,tag:BsSjWKwsYP2uwzu/DLBOuw==,type:str]
sops:
    age:
        - recipient: age1hwehr5ztfavd0p7x7n4fw8gfvzl05pj2u9v80xwqvhgnnmdfkexqspr0z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwV3dhQnhRSXRxdHZUKzd4
            ZDZqbEFwWDlTaGF6bEpaU0ptZWVLaGxCbFhjCk9sYUZOL2ZpNWowYi8ycDVGejQ3
            bmMzMHFremx0eTRhUjV5ZXYzaVRHdWMKLS0tIHZibDBjSjU2dDBnWlRhS1BaU2kr
            U0ExSnd5SHduT2hPbkdkNVYvdzEweVEKTknt87VcUwkqr0sWnnGCMe/TkpJp1fv7
            2UrevB69vD7omIEl59Gc1l+yGVK8PVSqMuWjyZz/pO4ltL9HSf8MHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T10:39:01Z"
    mac: ENC[AES256_GCM,data:8y7/PHUU63WxlbnJcjeF3qb9PWxcHfxtrPd1VRXf9VXK/zXlQiXaO4XauuJydl0EIzuyvHmrrnWNpt6OtA0kuqq5TcBzkGk8dMmsIbTy4PCDugmZzfXQKtCjL+9hw06kDpZr9S1KvVFOep/0pViNrpKvgzvcBZdiJi0PGNR8lew=,iv:/aBklRvf7H3ATEq9Fpcwpo5yT0kgAv9bMkXJ7ythxGs=,tag:LPfysZCpij215Tov0DSyLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:3cU=,iv:aYA+ftn8wYiQl1wzz5g1RFklDl/z8FcXXJFhaeN4lRM=,tag:g68fPau1b5qKAYO94zIWQw==,type:str]
kind: ENC[AES256_GCM,data:+s7MDLoh,iv:+i9OIYRWz+KyoJqNgZhUIQm1GZagaCpeaqr4zrx/zJU=,tag:34wZmZESZJu9J7S7r4qJQw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cqWyjBDjYQhvy4SGBOgA47Mj,iv:8UYR0m9f8hOZ4xJvCpEkQ3Nq8rDDVrCCCFkDrtjpq4U=,tag:bmcnNoUJsNFj19SQifdyzw==,type:str]
    namespace: ENC[AES256_GCM,data:wfFF9Iihn6A=,iv:3NKpnBJhwSYSlwS3ypy5yNZ9Y4FB94xvSHnsaiAhObM=,tag:MZp+e0xKwg+GYzL136kF0w==,type:str]
type: ENC[AES256_GCM,data:2wCAZvN9,iv:2HekUEUB5jy6zyFl7ivkPcfs4/UwTIlZP3be3xMIwSY=,tag:vjWaJOddmR+FonHMnPl0Ng==,type:str]
stringData:
    #ENC[AES256_GCM,data:rIRdYTd5UpDpVzyfh43jAZUnHK4RIhqeY84WzuJ3gfQ6YTz6IzoWbsQ=,iv:NonCkFDqKkVMH1R3EUsJD9C/Eedvpa2iF1MdwGLaI1A=,tag:TBNXmYZe30HT+RlE1waPvg==,type:comment]
    hub.cookie_secret: ENC[AES256_GCM,data:K6dkq+X+JICwNP5FuL57moUNH2EvXa0sMibEOnoXuQiHTPXeYW+aE992Oz78vi3AoeXqjJGwEYGgo+U09yXMJQ==,iv:BB81o69voAkaZCp4RfhRGWAHLSCEfc9Td3BFlwM5J2c=,tag:AMb9QfVGEPX1jmrZstCHbA==,type:str]
    proxy.secret_token: ENC[AES256_GCM,data:pwkyuSUGdx4JrCfTg7cQIenARxRxmfnhqg6hwqq6e7rYM9Xplu4p6BDk7ywouSujyTaBXBu1Gs64T04SPTFmxQ==,iv:ProIt3bseWUEry55wTDsr0zZGCgXxOvIKScP3sbX1c8=,tag:YXy+NhK5BkcHQJDO6YlzTQ==,type:str]
    crypt-key: ENC[AES256_GCM,data:dc+tGZJlXoUtX5tQZliFxalDMDiTEOJkZkP8ZGcbGVF558kvAVAUwgXofW7lYCm+5xrA+Uzfo4vXu4vK4yWZSQ==,iv:rF9avh1+1sZViopscDxXK7z4BNrCOheyYfHIk9gOvjo=,tag:/1ezmyfcQy2jgojvOvB3PA==,type:str]
    #ENC[AES256_GCM,data:xOrAJ1HK0zIIp4iM+MSQLxWHsFWjwwFMR9tTpZpteho/yE6zU3J8V9qCLMs7bys1vtPQiHvuVZaPfkF6ZDgYMTpcQD3OBaGQKHb4fBVWrIYEDUHWfQ==,iv:9+U0zsbrWj180sdaw4zK0CjW955cflZcCL5gG9rN+P8=,tag:i5xAcFYm2sF8lVWsb/5Dgg==,type:comment]
    #ENC[AES256_GCM,data:ls/8aTHXTZH3hmvkMVs9d/nVffNshyFw7sImZk367JmTPEs4QUEwIqRYnYnVis5HfnZrWYWnN7AvPXSUeA==,iv:XG/0cB9JBe5d5I252Mm+IRN5iNMzEKotNcZ2VfMkKkg=,tag:Lx0wyGc+8ztUPIc1Wo1vFg==,type:comment]
    auth.state.crypto_key: ENC[AES256_GCM,data:euWQn10KalOell8cLCYmHHLQCj3GZcpkxhVm7kINedxz95P7b9w7Fef/loDpSB2JcDUr6W/iTv9UpvwYOpr6mw==,iv:7qR2q9Vr4JxmYRTdPk9Hd6D10u6PJkHHp4ZYpS8md34=,tag:pI6zUWq01PEsVd4XDf1kBg==,type:str]
sops:
    age:
        - recipient: age1hwehr5ztfavd0p7x7n4fw8gfvzl05pj2u9v80xwqvhgnnmdfkexqspr0z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwV3dhQnhRSXRxdHZUKzd4
            ZDZqbEFwWDlTaGF6bEpaU0ptZWVLaGxCbFhjCk9sYUZOL2ZpNWowYi8ycDVGejQ3
            bmMzMHFremx0eTRhUjV5ZXYzaVRHdWMKLS0tIHZibDBjSjU2dDBnWlRhS1BaU2kr
            U0ExSnd5SHduT2hPbkdkNVYvdzEweVEKTknt87VcUwkqr0sWnnGCMe/TkpJp1fv7
            2UrevB69vD7omIEl59Gc1l+yGVK8PVSqMuWjyZz/pO4ltL9HSf8MHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T10:39:01Z"
    mac: ENC[AES256_GCM,data:8y7/PHUU63WxlbnJcjeF3qb9PWxcHfxtrPd1VRXf9VXK/zXlQiXaO4XauuJydl0EIzuyvHmrrnWNpt6OtA0kuqq5TcBzkGk8dMmsIbTy4PCDugmZzfXQKtCjL+9hw06kDpZr9S1KvVFOep/0pViNrpKvgzvcBZdiJi0PGNR8lew=,iv:/aBklRvf7H3ATEq9Fpcwpo5yT0kgAv9bMkXJ7ythxGs=,tag:LPfysZCpij215Tov0DSyLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
