apiVersion: ENC[AES256_GCM,data:fnY=,iv:bjn91LrUtpNnw8rUx0j/nAa7fDUYum0+hxaoBsZ02no=,tag:HCXfH9ajyPCEnFv4PAWthA==,type:str]
kind: ENC[AES256_GCM,data:iweExGIH,iv:b7m9o8FzP6vNv4/pbWa7KRdJuaofSZ0w2SL4s7AFX6c=,tag:Mih80yavp8XhdPROSADz4A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qAg5xyYs8hTapbQIYDcnR2E=,iv:lnouyPsmWyHhBdFlmcoOLj2M7aXVEpWR2bBxpUHqIeg=,tag:aZpnCtioRhQ/3QGm0fKVKw==,type:str]
    namespace: ENC[AES256_GCM,data:46xEn7h/sAg=,iv:W3Zjb+kyEvuSu4P2sJkxxQ+RF+UKAxx9mLc+pppzzCM=,tag:4P2smMn/t4VGP9NlvoNCUA==,type:str]
type: ENC[AES256_GCM,data:2ULFDhIl,iv:61EK396Pcyltu2A6Y/pzSmlj0z7E91VqQrZt1RrDH3Q=,tag:Fmx0FVpcCgQy1kR7DA94hQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:QrcQawIt8WDBOv0DeHzYqvpd1St/,iv:cbD5K0ybcJhRdKoJ8Jmre3RDEqV/ovoaD6wbKd66hQ0=,tag:9z37FMkPec3O4/QZbkqySQ==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:xtABe6p9q97Oi8l6joT4A8nxldkLIg//tSlRCUN6SGl70JPYGmBN/6hRuxeCLqg4ftc=,iv:5lg31IEhKD62Oqj3kBO8KYH/Fs+ST1NQ4c/kJ+edrxc=,tag:ZR3NHegUG7u4yuN7ZGjItA==,type:str]
    #ENC[AES256_GCM,data:TEFDODi+p51FjKKpdEbENKLQBir+Z0SlMTFD1epokgg=,iv:EOziODzOGyWw3ieDj9Y/t2QfBHpL6Q2hDy97fyYrt04=,tag:aU+jVFDmmbyCafVHcXFGhQ==,type:comment]
    #ENC[AES256_GCM,data:q1Zf6FfjXmeS95Q2nqVn4xNdWK2U+NkFzq9DgAZP7DSiCylc737aMJt8PJENHT4gHfcv88/lbKREIib4,iv:oDALDwLasZd8als04pXYizoojjjErlyJOrWmictmftA=,tag:WODnaae/M9dagiKd7MD7nQ==,type:comment]
    AUTHENTIK_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:uw84oCZQ80Zp7JNL1NwTvXpALpCofmRIb7qWhLN0poVgfTs=,iv:XRv840EHq8zdaF+hRJeJJJ4McrGOEXUT862/rCqziLc=,tag:Ma3IxkO3+LDCcSNS3GZS9Q==,type:str]
    #ENC[AES256_GCM,data:NPGvb4gfdVnrTvaXZVtdqw==,iv:/t75+TOMO62oEg8LQqY3ad5r3oTz9NjYEPPZcJo+7QI=,tag:pQnCkcIp0dkUQ2H52nAroA==,type:comment]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:R0HKv69WrBjZY1IK066Ue0o58ILZJNm0FTYscsWKz/0=,iv:qUn7AYj1bC1/a0h8qgs8wKc0tuLdglwA7IPMaMRvLdk=,tag:I7XcNLBcRxi/DKoJyzdVRQ==,type:str]
sops:
    age:
        - recipient: age1u7wrq6yktkprvkce38vhz358fmx7gunkyd0aflvu84d3wtvrrd7qvqwe26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNE5Fb1lBSGdCOEhiakRY
            OTlwL1JrZXcrdzdUK0pyRThFOUdIRnhUVGw0CmhDY0ZiMUc3c0VqM04zYm42VDQx
            M0o5c01BMmlLcjlmSTNYOHJ5bjRnSkUKLS0tIElEbjc1VEM0QzdSdkMzYWRJQ0c5
            SlJZbllnNWxIcGNFWGxuR3AyTzBxYWMKA81Y1DhohoCqeVvu52vcK7lMqW9Hhk/p
            XZ42CS9MIW3xjz7AGocCPI8yTQCdQKDZCKh4N4GpGPd3uhWGsRWwxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T13:52:57Z"
    mac: ENC[AES256_GCM,data:AiRFxTpbH3fnjoLykQWeHCBLT3dgsL4XDidv4+fXuYW8MpkhAfTA37bCKN4hBFyuRhQ4l1FXV6L1qF2OWrAVz4/sq/wXkJg8id2TU0jdWG6p8c2Qlhx6R0Yp9w6ywDYu5rWs4Wk2L2qxzstFSq/3tJTiEa+auU3gJvy66pEKrOY=,iv:JPXNYAMCRuUqi6oZJ1byUbH8FanqH1HEvWOh/4t0r4g=,tag:CjCBBFFNXj20mLBhmspUeg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
