apiVersion: ENC[AES256_GCM,data:STA=,iv:bjn91LrUtpNnw8rUx0j/nAa7fDUYum0+hxaoBsZ02no=,tag:J5ft42ryhXpvMWYwcoeOjw==,type:str]
kind: ENC[AES256_GCM,data:0ZfeROzN,iv:b7m9o8FzP6vNv4/pbWa7KRdJuaofSZ0w2SL4s7AFX6c=,tag:D5cBYfXNxP1jgWfP9ibhZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lakpiiQocrJEcnzs07sOM1Q=,iv:lnouyPsmWyHhBdFlmcoOLj2M7aXVEpWR2bBxpUHqIeg=,tag:djF7aFyZM6Ct0trWXWa7BA==,type:str]
    namespace: ENC[AES256_GCM,data:7WBuAbdoC6w=,iv:W3Zjb+kyEvuSu4P2sJkxxQ+RF+UKAxx9mLc+pppzzCM=,tag:vNb+MiIYNJzhhXyDcPuYlw==,type:str]
type: ENC[AES256_GCM,data:Lstk8Ku3,iv:61EK396Pcyltu2A6Y/pzSmlj0z7E91VqQrZt1RrDH3Q=,tag:5zz4kq7sApEC+uZrLhA2nw==,type:str]
stringData:
    #ENC[AES256_GCM,data:1MFPvO5FfA50g+YPTib7j28Voe9e,iv:cbD5K0ybcJhRdKoJ8Jmre3RDEqV/ovoaD6wbKd66hQ0=,tag:4jHm5lnV9wRJ17HfmZn/4Q==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:zDRavib6liHOYp9hl3C44cZ12duMBvcMh5M8ezlkmJg3T94IKQszCb0X41qi9KDywVw=,iv:5lg31IEhKD62Oqj3kBO8KYH/Fs+ST1NQ4c/kJ+edrxc=,tag:99rVZTG4XxBiwbRfwkOmmQ==,type:str]
    #ENC[AES256_GCM,data:jln17SBrSxIgHhWVMIFHyP1LrlrmeNRDyt0d/esPqHs=,iv:EOziODzOGyWw3ieDj9Y/t2QfBHpL6Q2hDy97fyYrt04=,tag:90IPS+lIQbrMq2GsvBtAUw==,type:comment]
    #ENC[AES256_GCM,data:861V6p4+o+MtRmKJh9JobpZI9Wru6krPxJQjV2WCkkhK0wxHFP31UamotSfBgP4EPZZC0pbgfJ4xxf8e,iv:oDALDwLasZd8als04pXYizoojjjErlyJOrWmictmftA=,tag:Vja5txUbAMtIXTJbRZCNYA==,type:comment]
    AUTHENTIK_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:3Kfdun88mpOoSttQcQUelu/zq+0NjbaAU7uimQv8yW917JI=,iv:XRv840EHq8zdaF+hRJeJJJ4McrGOEXUT862/rCqziLc=,tag:GigEVw/HO4x15eYFP5FXfA==,type:str]
    #ENC[AES256_GCM,data:bOJ5h6USY4QraZtv0rN85A==,iv:/t75+TOMO62oEg8LQqY3ad5r3oTz9NjYEPPZcJo+7QI=,tag:Hwtw8fT6jo2CHrHqfH92gQ==,type:comment]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:1oWUWj5mSYF9CtL8yIXejnXhjFJRdeTLMLuCQK0raCs=,iv:qUn7AYj1bC1/a0h8qgs8wKc0tuLdglwA7IPMaMRvLdk=,tag:zudJqwMiKwMRq3NFApAcAQ==,type:str]
sops:
    age:
        - recipient: age1hwehr5ztfavd0p7x7n4fw8gfvzl05pj2u9v80xwqvhgnnmdfkexqspr0z6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTGVpL0duQ2ZDaVhUUmRO
            NU84MEdRaUkyN1BtNUU3ZnRlK3NTZDU2b1dJClM4L0JaME9HTEdodithYmpxTFJp
            WFNBVXBWRGM1cW1ETWhWNy81UyszazAKLS0tIDFpYm5nclM4bkh1RXJ6azN4eVht
            YlhjaU04ZVcvN2FKeWNETHNweFc0bE0KJOllt4S4EHe7EBM4hS8TPs6Pg15++jQV
            CvQUOllKoIqmaucfIZm/8/crH6OTFdhR1/pNFBlWJ2RuDhci6IzQXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T10:40:07Z"
    mac: ENC[AES256_GCM,data:lkMSHAVWDGzqGhWmexvJpC/zRq4bu3EKqTy3zw92MpdmUYaeYHDC8Yc7h9tywvR4/wBW8p5d5SkYZ870BmWHwTinCzXKkR7lEbTBEH0QK1IqcdrL/0aXo4Dk2Bc3yKZGw5MTuLkR82x9ouOTIrmZnNz4Nw9YXHRGZZbkmOxos1Y=,iv:EBG7XOYFJdKJBjllbpb5Crg/qo9QAtgb+Qww0zF+8WY=,tag:SoFjT6YXgtzTXuSKNjIt5Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
