# SopsSecret for shared PostgreSQL credentials
# This wraps the encrypted secret and will be decrypted by the SOPS operator
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgres-credentials-sopssecret
    namespace: cit-postgres
spec:
    secretTemplates:
        - name: postgres-credentials
          type: Opaque
          stringData:
            #ENC[AES256_GCM,data:K+/AwEieNICeC1d7QGxeWCHdfNlOmzlzd+Gx6Fe2,iv:5Nv8vYjeMvZKA/y+Jx4IdKs2R99GDZwY/IgX04+vr1Q=,tag://FCYlGskULtK+hTIy4d9A==,type:comment]
            postgres-password: ENC[AES256_GCM,data:pl/5I8S7PejPBEhD5S7fZp74F/VGtfxV8JFSqVvRxg4=,iv:e80Q/go678Wsaj4biRD95UQu1+tNAdqrsFqOyZ34Hbc=,tag:xoC5Zxu2KJ3/l/8Ldjqxtg==,type:str]
            #ENC[AES256_GCM,data:OWvIWe9Wx5oEbJVcAMEBqObP9qf7gMbxgNFnGZs=,iv:uhbGgpYz6pu93J+6gMANzecNt/qYrHqE71Q7dkk15qI=,tag:RkT+f7+5totxRB3sLqDZ9g==,type:comment]
            password: ENC[AES256_GCM,data:o7DTLQCzsUOrXjHFmsKKsQuohvs47D3MzCjHRg2sUv8=,iv:zIzIUdfB0GrU3NiRxuHa254L/1L+7Gk4riCiRCitReI=,tag:oi3RRVieAfP2nO43+74YBQ==,type:str]
sops:
    age:
        - recipient: age1u7wrq6yktkprvkce38vhz358fmx7gunkyd0aflvu84d3wtvrrd7qvqwe26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRGMyd0ZEKzF5cU5ETHFQ
            OXluMjM2TmZjT2p1dVBpSGN1R2NJN0xZeFhRCk5NUU5kQUVGdWZrcmluNzVUNjVQ
            RXFpd0dQTTV2dWlZUXZMN2Y1aUNidHcKLS0tIGRuVCsrN0kxaXNqNnZhMEJETEoz
            cVdJRi93N1VzazZzYkFzSXRpeEVBdEEKK1AupaZoO3MfGJR0SvtovII7n57mARrU
            bMI8LCp7ujn9P559XuQ5AKnD6jTHjmXcHLahgcYo7f6TMvO/NkV2RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T15:18:47Z"
    mac: ENC[AES256_GCM,data:vxDE2vjKVf1Nyq16gs0yuMgNNNxg6AY5rUl6KPYegrw9/BdE3t+w1jIhMz1IjACsNiaEYyjQDZN2mf1ws662hlqJh429q83/CXpAM5pAlITCiJFxuncdKd/7L/uVcVNJp+bcOUjlm2YV30Qk0xvVrufrQxec5KcVYS/rHrDwN9c=,iv:S5xXeksDV4X8/R2b2RjKfPWhWJ6tQ6O/N5AqwJUpQXo=,tag:Sp+IwM/NqHVCl1PDtJPoWQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
